### ISSUE TITLE
关于提高MLSNews的新闻总结能力

### ISSUE THREAD

**Issue by blocklee** [f-labs/MLSNews#14]
MLSNews《未闻》作为一个偏向技术特性的、具有新闻媒体性质的板块，对于每一条新闻，都需要精益求精，有以下要求或建议：
1、标题是一个高度概括性的、并能点明主旨的存在；
2、新闻描述，是概括性的总结出全文中心思想，作为一个偏技术特性的媒体，需要抓取文章（或新闻）中的关键（技术）点，描述出是谁，通过什么样的方法（技术），达到了什么样的结果。

方法提供：文章摘要或新闻的引言部分本身会多文章做一些主旨概括，但这还不够，我们需要大概了解一下文章的内容，去抓取文章中提到的关键技术（实现方法），以及达到的结果。

举例：
“很多人对闪电网络的局限性都很感兴趣——究竟闪电网络能做些什么，或又做不到什么。今天就来和大家理清一下闪电网络的应用范围。”

这样的语言，并不适合作为一个新闻媒体的输出语言，特别是后边那句话，咱们是要说新闻，说事，具体的什么事，是要给叙述体，不是在给一场发言的做引言。改进举例：

“很多人对闪电网络的局限性很感兴趣——但是闪电网络究竟能做些什么，或又做不到什么，这个分界线在哪里呢？Alex Bosworth（这个人是什么身份可以加上，闪电网络的某一个开发者？） 分别从闪电网络的基础结构层、协议层、生态系统规模等多个角度分析了闪电网的发展限制。“

像”今天要干什么。。。“这样的语言属于第一人称语言，咱们的新闻属于第三人称叙述体！

**Comment by yatingzhou** [comment]
但从今天的三篇文章来看，文章内容质量确实是与我们研究的方向结合了。建议在每篇文章下面（如果看了的话），可以做适当的输出相当于读书笔记，也为自己以后输出这样的文章做铺垫。
