### ISSUE TITLE
use .gitignore

### ISSUE THREAD

**Issue by dindinw** [f-labs/MLSNews#3]
remove the .idea folder

**Comment by blocklee** [comment]
use '.gitignore' as the name of a txt , then write ' .idea' in the txt ?

**Comment by dindinw** [comment]
@blocklee google is your friend 
https://www.atlassian.com/git/tutorials/saving-changes/gitignore
https://help.github.com/en/articles/ignoring-files

**Comment by dindinw** [comment]
BTW, please close the issue if you have done
